# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge

timezone: Asia/Shanghai

paginate: 5
paginate_path: "/blog/page/:num/"
gems: [jekyll-paginate]

comments: true

sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: WenBlog
description: "Personal Blog site about python, javascript, c# and some computer things"
keywords: "blog, python, javascript, c#, coding"
url: er3456qi.github.io
baseurl: ""
# baseurl: "/end2end"

# Localization strings
str_blog: 博客
str_about: 关于
str_home: 返回主页
str_archive: 归档
str_blog_archive: 所有博客

# google_analytics: UA-52446115-1

repo: https://github.com/er3456qi

# Disqus
# disqus_shortname: "fernandomoreira"
# disqus_site_shortname: "fernandomoreira"

# Author settings
author:
  name      : Wnbot
#   job       : Frontend Engineer
  buzz1     : 喜欢有创意有脑洞的事，是个有趣的人
  buzz2     : 人生苦短，我用Python、C#、Javascript 啊哈哈哈
  thumb     : /images/author.jpg
  email     : er3456qi@outlook.com
#   url       : http://nandomoreira.me
  github    : http://github.com/er3456qi
  weibo     : http://weibo.com/u/1717207925
  twitter   : https://twitter.com/er3456qi
#   facebook  : http://facebook.com/er3456qi
  segmentfault  : https://segmentfault.com/u/er3456qi

# navbar pages
navbar:
  - slug: blog
    title: 博客
  - slug: archive
    title: 归档
  - slug: about
    title: 关于
#   - slug: projects
#     title: 项目
  # - slug: about
  #   title: About
  # - slug: blog
  #   title: Blog
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", ".sass-cache"]
