# Site settings
title: Wen Blog
name: Wen Blog # your name
email: er3456qi@gmail.com # your email address
description: >
    A Personal Blog Site. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://er3456qi.github.io" # the base hostname & protocol for your site
twitter_username: er3456qi # your Twitter username
github_username: er3456qi # your Github username
disqus_username: a-wnbot-xyz # your disqus username

# google-analytics: UA-75034651-1 # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
