# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'wnbot-xyz'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Archive', path: 'menu', url: 'archive.html'}
- {name: 'Category', path: 'menu', url: 'category.html'}
- {name: 'Tags', path: 'menu', url: 'tags.html'}
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/er3456qi'}
- {icon: 'twitter', link: 'https://twitter.com/er3456qi'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/er3456qi/'}
- {icon: 'envelope', link: 'mailto:er3456qi@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
